require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rake

AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
    - db/schema.rb
    - coverage/**/*
    - log/**/*
    - tmp/**/*
    - public/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.1.1
  NewCops: enable

Layout/LineLength:
  Max: 130

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 10
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  IgnoredMethods:
    - create_table
  Exclude:
    # Examples are mostly kept in a 1:1 file mapping, and examples can get quite long.
    - 'spec/**/*'

Metrics/AbcSize:
  Description: A calculated magnitude based on number of assignments,branches,
    and conditions.
  Max: 19
  IgnoredMethods:
    - change
    - query_string

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  Description: Checks for trailing comma in hash literals.
  EnforcedStyleForMultiline: consistent_comma

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing
  SupportedStyles:
    - leading
    - trailing

Style/GuardClause:
  Enabled: true
  MinBodyLength: 1

RSpec/FilePath:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 15

RSpec/ContextWording:
  Prefixes:
    - for
    - when
    - with
    - without
